### ISSUE TITLE
can I use the icons for publication?

### ISSUE THREAD

**Issue by zhulibing** [duerrsimon/bioicons#106]
Hi I am using some of the icons in my diagram for publication. How to cite them properly?  Thank you so much.

**Comment by duerrsimon** [comment]
![image](https://github.com/duerrsimon/bioicons/assets/16979577/e565d0dc-760a-44b4-a3a8-fbbb0b353c1d)
![image](https://github.com/duerrsimon/bioicons/assets/16979577/db59b3ab-cff2-479b-8d39-e95c5627a63f)

For each icon that you're using you can click on the Attribute? button and get a summary of what you are allowed to do under what conditions. You can also copy a sample attribution to your clipboard. 

This attribution you put in the figure caption or in the acknowledgements section of your article.

**Comment by zhulibing** [comment]
Thank you so much for your kind help. I really appreciate that.
