### ISSUE TITLE
Add frontend license filter?

### ISSUE THREAD

**Issue by dcroote** [duerrsimon/bioicons#164]
I think it could be useful to have a dropdown filter like exists for "All icons",  in order to, say, restrict the search to CC0.

![image](https://github.com/duerrsimon/bioicons/assets/13989647/998dc486-5f78-4b5d-96e9-61cf64be3170)

It should help that the `static/icons` directory is already organized by license

**Comment by duerrsimon** [comment]
Planned as part of #100
