### ISSUE TITLE
Add drawings for aortic diseases

### ISSUE THREAD

**Issue by SterArcher** [duerrsimon/bioicons#20]
I love what this project is doing, great work! Please add drawings icons for

- [ ] aortic dissection
- [ ] aortic intramural hematoma
- [ ] penetrative Atherosclerotic ulcer
- [ ] Stanford classification of aortic dissection

Thank you and keep up the good work!

**Comment by Kekananen** [comment]
@SterArcher I'll draw these and donate them to the project. Always love open-source projects like this, just give me a few weeks to create them as I'll have some free time coming up.
