### ISSUE TITLE
Remove background from images

### ISSUE THREAD

**Issue by CMonck** [duerrsimon/bioicons#5]
Hey :) Love your work and am super appreciative that you are letting others use it for free, I think it's great!
A comment I would have from my first attempt at using it would be that your images all have white backgrounds. This makes it hard to combine them into more complex figures eg. adding a plasmid / transcription / translation scheme inside one of your empty cells, or adding the images into figures which have non-white backgrounds. Not sure how easy it is to fix, but thought I would flag it in case :) 
Thanks again for your awesome content!

**Comment by duerrsimon** [comment]
I am assuming you are copy pasting the images directly from the site into a non-vector graphics program, correct?  (if you are using inkscape the support to paste in svgs from the clipboard is only coming in the next version, so here you still need to switch to direct download in the toolbar)
The copy pasted images are drawn on the fly on a html canvas and then rendered as image with white background. I'll see if I can make this transparent. 

But, anyway you should really use the SVG vector images directly, they dont have a background AND you can edit all the shapes, change colors and you can export them to any resolution without loss of quality. 

Vector images you can use in Inkscape, Illustrator, CorelDraw and you can import them e.g into GIMP, Photoshop etc in the desired size.

**Comment by CMonck** [comment]
Thanks for this! I’m new to building figures, so I appreciate you pointing me in the right direction :)

________________________________

**Comment by duerrsimon** [comment]
closing this for now. I checked and the canvas needs to have a background otherwise it is black and white is the better default imho. Maybe if there is interest from more users i'll add transparent pngs generated from the svgs serverside but SVG is anyway preferable.
