### ISSUE TITLE
Name possibly spelt incorrectly in many places

### ISSUE THREAD

**Issue by mattwarkentin** [duerrsimon/bioicons#6]
Hi @duerrsimon,

Love the icon set. Thanks for creating this great resource.

Seems like your last name might be spelt wrong in many places (e.g. `icons.json`, `authors.json`, website). See below for an example.

![Screen Shot 2021-04-26 at 5 06 32 PM](https://user-images.githubusercontent.com/27825069/116150782-d2bdac00-a6b1-11eb-8567-b59315070b14.png)

I could be wrong, but just wanted to make sure you get proper attribution.

**Comment by duerrsimon** [comment]
Hi matt, thanks for your comment! 
Happy to make you acquainted with the intricacies of having an umlaut in your name :D 
In german we use ä, ö, ü and one can write these also using ae, oe or ue.  

All my icons are under CC0 anyway so you don't need to credit me whatsoever :)

**Comment by mattwarkentin** [comment]
🤦‍♂️
